### ISSUE TITLE
Unsatisfactory video results

### ISSUE THREAD

**Issue by Condor9** [a1600012888/PhysDreamer#15]
Hi, I run the code based on your default arguments, but the result of the generated video is almost completely black, with unclear target objects in just a few frames. What's the reason for this? The result of running the code is as follows:

loading scene params from:  C:\PhysDreamer-main\projects\inference\configs\carnation.py
=> loading camera from blender format transforms_train.json
=> loading camera from blender format transforms_train.json
len of test dataset 209
load gaussians from: data/physics_dreamer/carnations/point_cloud.ply ... num gaussians:  1037279
loaded 130812 clean points from:  data/physics_dreamer/carnations\clean_object_points.ply
init young modulus:  2140628.25 poisson ratio:  0.264644056558609
scale, shift tensor(2.8624, device='cuda:0') tensor(0.7803, device='cuda:0')
simulation aabb:  tensor([[0.2611, 0.5404, 0.1217],
        [0.3752, 0.7084, 0.3275]], device='cuda:0')
Downsample with ratio:  0.1
=> staring downsample with kmeans from  133564  points to  13356  points
=> downsample with kmeans takes  159.35061621665955  seconds
Downsampled to:  13356 by 0.1
Number of non-empty voxels:  99
Max points in voxel:  841.0
Min points in voxel:  0.0
Avg points in voxel:  134.9090909090909
Warp 0.10.1 initialized:
   CUDA Toolkit: 11.5, Driver: 12.5
   Devices:
     "cpu"    | Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
     "cuda:0" | NVIDIA GeForce RTX 2080 Ti (sm_75)
   Kernel cache: C:\Users\AppData\Local\NVIDIA Corporation\warp\Cache\0.10.1
(13356,) torch.Size([13356])
Module physdreamer.warp_mpm.mpm_data_structure load on device 'cuda:0' took 4.20 ms
Particles initialized from torch data.
Total particles:  13356
Module mpm_data_structure load on device 'cuda:0' took 3.63 ms
number of freeze grid 24
num freeze pts in total 1835 num moving pts 11521
Module mpm_utils load on device 'cuda:0' took 244.40 ms
=> zero init the last layer for Spatial MLP
=> zero init the last layer for Spatial MLP
=> loading:  models/physdreamer/carnations/model\velo_fields.pt
=> loading:  models/physdreamer/carnations/model\sim_fields.pt
torch.Size([13356]) 6986 apply force mask
  0%|          | 0/90 [00:00<?, ?it/s]Module physdreamer.warp_mpm.mpm_solver_diff load on device 'cuda:0' took 2.66 ms
100%|██████████| 90/90 [04:17<00:00,  2.86s/it]
number of simulated frames:  91 num camera viewpoints:  91
save video to  output/carnations/demos\inference_demo_carnation_sv_gres64_substep768_model_0_force_1_mag_2.0_point_0_movingcamera_camid_0_inference_demo_carnation_sv_gres64_substep768_model_0_force_1_mag_2.0_point_0.mp4

**Comment by a1600012888** [comment]
Can you upload the video here, then I can try to debug.

**Comment by Condor9** [comment]
Thanks for your reply, it has been resolved!

**Comment by maohaotian** [comment]
I encountered the same problem. Could you please tell me how you solve this?

**Comment by Andy-Shao19** [comment]
> Thanks for your reply, it has been resolved!谢谢您的回复，已解决！

I encountered the same problem. Could you please tell me how you solve this?
