### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by ExcitedButter** [a1600012888/PhysDreamer#16]
Thanks for the great work. May I ask if the training code is released or are there any  training instructions? I would really appreciate your help!

**Comment by FedericoVasile1** [comment]
Hi, 

thanks @a1600012888 for your great work and congratulations for being accepted to ECCV!

any updates or releasing the training code?

Thanks

**Comment by a1600012888** [comment]
Hi, 
can you share me your email, I can send you the uncleaned source code. 

I will try to clean the code soon.

**Comment by mengsiwei** [comment]
Hi @a1600012888,

Can you share me a copy of training code of this awesome work? My email is siweim@unr.edy. Thanks!!!

**Comment by Elowen-surj** [comment]
Hi @a1600012888,
Can you also share me the uncleaned source code of this work? My email is surj@mail2.sysu.edu.cn.
Thank you very much!

**Comment by haoz19** [comment]
Hi @a1600012888,
Can you also share me the uncleaned source code of this work? My email is [haoz19@illinois.edu](mailto:haoz19@illinois.edu). Thanks a lot!

**Comment by zz7379** [comment]
Congratulations on being accepted to ECCV and meet you at Milan! Could you also share the training code? My email is wangxinzhou@tongji.edu.cn.

**Comment by Hansello218** [comment]
Hello, @a1600012888!
Thank you for providing such excellent work. I'm very interested in this work and hope you can share your uncleaned code with me~ I would greatly appreciate it! My email is: chechao218@stu.suda. edu.cn

**Comment by Hansello218** [comment]
Hello, @a1600012888!
Thank you for providing such excellent work. I'm very interested in this work and hope you can share your uncleaned code with me~ I would greatly appreciate it! My email is:  chechao218@stu.suda.edu.cn. Thanks a  lot！

**Comment by ReFantasy** [comment]
Hi @a1600012888,
Can you also share me the uncleaned source code of this work? My email is 309741309@qq.com. Thanks!

**Comment by Shi-qingyu** [comment]
Hi @a1600012888,
Could you please share the uncleaned source code for this work as well? You can send it to me at [q.y.shi@stu.pku.edu.cn](mailto:q.y.shi@stu.pku.edu.cn).
Thank you so much!

**Comment by becauseofAI** [comment]
Hi @a1600012888,
Can you also share me the uncleaned source code of this work? My email is [yking@pku.edu.cn](yking@pku.edu.cn).
Thank you very much!

**Comment by CHNxindong** [comment]
Hi @a1600012888,
Thanks for your great work. Could you please share the uncleaned training code with me? I would greatly appreciate it! My email is: dong-x23@mails.tsinghua.edu.cn.

**Comment by youngju-na** [comment]
Hi @a1600012888, 
Could you please share the training code with me? My email is: [yjna2907@kaist.ac.kr](mailto:yjna2907@kaist.ac.kr).

**Comment by Svithjod** [comment]
Hi @a1600012888,
Thanks for your great work. Could you please share the uncleaned training code with me too? My email is: [svithjod1019@gmail.com](mailto:svithjod1019@gmail.com).
