### ISSUE TITLE
How to run this job with 40G VRAM？

### ISSUE THREAD

**Issue by XiaokunSun** [a1600012888/PhysDreamer#4]
Thank you for your excellent work! Since I only have roughly 40G VRAM, I can't run this awesome job on my local machine, is it possible to lower the video memory by modifying the config file? If not can you provide some examples of low VRAM, looking forward to your reply!

**Comment by a1600012888** [comment]
Hi, 40GB memory machine is enough. 

After downloading the data and model from huggingface, please go to folder `projects/inference/`, and run `python3 demo.py --scene_name carnation --apply_force --force_id 1  --point_id 0 --force_mag 2.0 --cam_id 0`.  

I think 40 GB is fine for this scene, if you encounter OOM at any scenes, you can change to downsampling function following: https://github.com/a1600012888/PhysDreamer/tree/main/projects/inference 

It's the pointcloud downsampling function that bottleneck the memory now. (a GPU implementation of Kmeans)

**Comment by XiaokunSun** [comment]
Thank you! It works!
