### ISSUE TITLE
Implementation of anisotropic regularization on gaussians

### ISSUE THREAD

**Issue by haoyuhsu** [a1600012888/PhysDreamer#6]
Hi, 

I am really impressed by this work and still figuring out the details.
I would like know if you have kept the implementation of anisotropic regularization in the codebase or not.
Thanks a lot!

**Comment by a1600012888** [comment]
I added this part to the original gaussian splatting training code.  

```python
# add anisotropic reg:
gaussian_scaling = gaussians.get_scaling # [N, 3]
aniso = torch.max(gaussian_scaling, dim=1)[0] / (torch.min(gaussian_scaling, dim=1)[0] + 1e-5)
aniso_clip = torch.clamp(aniso, args.aniso_thres, None) - args.aniso_thres
loss_aniso = torch.mean(aniso_clip)
```

**Comment by haoyuhsu** [comment]
Thanks for your sharing!
